apiVersion: v1
kind: Service
metadata:
  labels:
    app: hashfab-fe
  name: hashfab-fe
spec:
  type: LoadBalancer
  selector:
    app: hashfab-fe
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hashfab-fe
  name: hashfab-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashfab-fe
  template:
    metadata:
      labels:
        app: hashfab-fe
    spec:
      containers:
      - image: dgunjetti/hashfab-fe
        name: hashfab-fe
        ports:
        - containerPort: 80
